language: r
warnings_are_errors: false
sudo: required

r_build_args: --no-build-vignettes --no-manual --no-resave-data
r_check_args: --no-build-vignettes --no-manual

apt_packages:
    - libnetcdf-dev
    - netcdf-bin
    - gdal-bin

r_packages:
    - devtools
    - rgdal
    - ncdf4
env:
    global:
        - _R_CHECK_FORCE_SUGGESTS_=False
        - _R_CHECK_CRAN_INCOMING=False

