language: r
warnings_are_errors: false
sudo: required
r_build_args: --no-build-vignettes --no-manual --no-resave-data
r_check_args: --no-build-vignettes --no-manual
install:
    - Rscript -e 'install.packages("devtools", repos="http://cran.rstudio.com")'
env:
    global:
        - _R_CHECK_FORCE_SUGGESTS_=False
        - _R_CHECK_CRAN_INCOMING=False

